{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\nUsers/tf/Desktop/PycharmProject/Pytest/Demo/TestCase/test_report.py:14: Exception"}, "start": 1583221463408, "stop": 1583221463408, "uuid": "825bd13d-56bc-4d06-a92e-8802302ac66b", "historyId": "d7a410e035dcaee8a4a0d4df35b1eb6f", "testCaseId": "45d9a87b99ea9b7b94b411bc48276b00", "fullName": "TestCase.test_report#test_broken", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_report"}, {"name": "host", "value": "TwistFatedeMac-mini.local"}, {"name": "thread", "value": "1286-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_report"}]}